[package]
name = "pentultimate_solver"
version = "0.1.0"
authors = ["Zeke Baker <zbaker@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.5.0", features = ["serialize"] }
env_logger = "0.8.3"
hexf = "0.2.1"
fnv = "1.0.7"
gltf-json = "0.16.0"
json5 = "0.3.0"
lazy_static = "1.4.0"
libc = "0.2.99"
log = { version = "0.4.14", features = ["serde"] }
serde = "1.0.125"
rand = "0.8.4"
ron = "*"
static_assertions = "1.1.0"

[dev-dependencies]
criterion = "0.3.4"
# wgpu = "0.7.1"

[features]
const_fn_floating_point_arithmetic = []
io_read_to_string = []

# specialization = []

default = ["const_fn_floating_point_arithmetic", "io_read_to_string"]

[[bench]]
name = "criterion_benchmarks"
harness = false