[package]
name = "pentultimate_solver"
version = "0.1.0"
authors = ["Zeke Baker <zbaker@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5.0"
env_logger = "0.8.3"
hexf = "0.2.1"
fnv = "1.0.7"
gltf-json = "0.16.0"
lazy_static = "1.4.0"
log = "0.4.14"
serde = "1.0.125"
json5 = "0.3.0"