binop_separator = "Back"
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
enum_discrim_align_threshold = 120
group_imports = "StdExternalCrate"
hard_tabs = true
# Until "One" doesn't cause an error...
# imports_granularity = "One"
imports_granularity = "Preserve"
imports_indent = "Block"
imports_layout = "Vertical"
indent_style = "Block"
max_width = 120
newline_style = "Unix"
overflow_delimited_expr = false
space_after_colon = true
space_before_colon = false
spaces_around_ranges = true
tab_spaces = 4
use_small_heuristics = "Max"